# -*- coding: utf-8 -*-
"""Saneamiento de los metadatos de un .docx.

python-docx firma cada documento que crea: deja «python-docx» como autor y
«generated by python-docx» como comentario en docProps/core.xml, y arrastra del
fichero plantilla un docProps/app.xml que declara «Microsoft Macintosh Word»
como aplicacion. Nada de eso se ve abriendo el documento, pero aparece en las
propiedades del fichero, que es justo donde mira quien quiera saber quien ha
escrito un manuscrito supuestamente anonimo.

Para la revision ciega el campo de autor debe quedar vacio. Para la carta de
presentacion, que no es anonima, se pone el nombre real.
"""
import datetime
import re
import shutil
import zipfile

from docx import Document


def limpiar(path, autor="", titulo=None, asunto="", aplicacion="Microsoft Office Word"):
    """Reescribe las propiedades del documento. autor='' lo deja anonimo."""
    doc = Document(path)
    cp = doc.core_properties
    cp.author = autor
    cp.last_modified_by = autor
    cp.comments = ""
    cp.category = ""
    cp.content_status = ""
    cp.identifier = ""
    cp.subject = asunto
    cp.keywords = ""
    cp.version = ""
    cp.revision = 1
    # La plantilla interna de python-docx trae 2013-12-23 como fecha de creacion,
    # que en un manuscrito de 2026 llama la atencion sin motivo.
    ahora = datetime.datetime.now().replace(microsecond=0)
    cp.created = ahora
    cp.modified = ahora
    if titulo is not None:
        cp.title = titulo
    doc.save(path)

    # docProps/app.xml no lo gestiona python-docx: hay que tocarlo en el zip.
    tmp = path + ".tmp"
    with zipfile.ZipFile(path) as zin, zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            datos = zin.read(item.filename)
            if item.filename == "docProps/app.xml":
                x = datos.decode("utf-8")
                x = re.sub(r"<Application>.*?</Application>",
                           "<Application>%s</Application>" % aplicacion, x)
                x = re.sub(r"<Company>.*?</Company>", "<Company></Company>", x)
                x = re.sub(r"<Manager>.*?</Manager>", "<Manager></Manager>", x)
                x = re.sub(r"<Template>.*?</Template>", "<Template></Template>", x)
                datos = x.encode("utf-8")
            zout.writestr(item, datos)
    shutil.move(tmp, path)


def informe(path):
    """Devuelve las propiedades que quedan con contenido, para comprobar."""
    cp = Document(path).core_properties
    campos = ("author", "last_modified_by", "comments", "title", "subject",
              "keywords", "category", "content_status", "identifier", "version")
    return {k: getattr(cp, k) for k in campos if getattr(cp, k)}
